### ISSUE TITLE
Possible callbacks 

### ISSUE THREAD

**Issue by nhaberl** [tameemsafi/typewriterjs#1]
Would be great to have the Chance of registering callbacks in a fluent manner alter each string is written for example. 
Would be great for guided walk throughs on a website. 

Considering it making async also with promises.

**Comment by tameemsafi** [comment]
Thanks for your feedback.

I am currently working on allowing HTML tags inside of the strings, but I will also add callbacks to each of the available methods.

**Comment by schmolzp** [comment]
Are you still planning on adding callback methods? This would be really useful to have some control after typing has finished. Thanks!

**Comment by bhaskar-nair2** [comment]
@tameemsafi Would make this script extremly useful if we have callback functions.

**Comment by tameemsafi** [comment]
I have added callback function now, which can be chained after each method.

You can do the following:

```
const typewriter = new Typewriter('#app');
typewriter.typeString('Hello world!')
  .callFunction(() => {
    console.log('Finished typing string');
  })
  .start();
```

**Comment by antoniojps** [comment]
@tameemsafi Well done, great update!  🎉
