### ISSUE TITLE
Integrating with React

### ISSUE THREAD

**Issue by whenitrainsitpours** [tameemsafi/typewriterjs#10]
How to use it with React?  Like this site https://wild.as/, thanks!

**Comment by tkroll** [comment]
Just do: 
`import '/your-path/typewriter.min.js'`

Add a span:
`<span id="typed"></span>`

then:

```
const el = document.getElementById('typed')
const strings = ['Some', 'text', 'goes', 'here']
new window.Typewriter(el, {
  strings,
  autoStart: true,
  loop: true
})
```

**Comment by tameemsafi** [comment]
You can now import the component in react. Please see [npm repo](https://www.npmjs.com/package/typewriter-effect).
