### ISSUE TITLE
Missing method to erase all in one time

### ISSUE THREAD

**Issue by seangoogoo** [tameemsafi/typewriterjs#105]
Not really about an issue but maybe a missing method : if I have to write a very long series of sentences and then replace it by another very long series of sentences, calling the 'deleteAll' method can be very long and boring for the user and there is no method to erase all the content in one time. 

I figured out a way to do it with the 'callFunction' method but maybe you could add it natively.

Here is my method (excuse my poor javascript way of writing it) : 

`    function eraseAll(twObj) {`
`     twObj.state.elements.wrapper.innerHTML = '';`
`			twObj.state.visibleNodes = [];`
`    }`

`    const twObject = new Typewriter('#typewriter', { `
`     delay: 35,`
`      loop: true`
`    }).typeString('Duplexque isdem diebus acciderat malum, quod et Theophilum insontem atrox interceperat casus, et Serenianus dignus exsecratione cunctorum, innoxius, modo non reclamante publico vigore, discessit.').pauseFor(2000).callFunction(() => {`
`      eraseAll(twObject);`
`    }).typeString('Quanta autem vis amicitiae sit, ex hoc intellegi maxime potest, quod ex infinita societate generis humani, quam conciliavit ipsa natura, ita contracta res est et adducta in angustum ut omnis caritas aut inter duos aut inter paucos iungeretur.').start();`

**Comment by tameemsafi** [comment]
You can re-create the typewriter instance on the same html element, which will reset everything.

See example:
https://jsfiddle.net/qjwbv3s8/2/

```js
const createInstance = () => {
  let instance = new Typewriter('#typewriter')

  instance
    .typeString('testing first string')
    .pauseFor(1000)
    .callFunction(() => {
      instance = new Typewriter('#typewriter')
      instance
        .typeString('testing second string')
        .pauseFor(1000)
        // Add this for looping
        .callFunction(createInstance)
        .start()
    })
    .start()
}

createInstance()
```
