### ISSUE TITLE
Next line typing

### ISSUE THREAD

**Issue by ADARSHputhane** [tameemsafi/typewriterjs#109]
how to make typewriter type in next line

**Comment by ADARSHputhane** [comment]
i got to use <br> for now. If there is any other method please tell me. i tried using escape character but its not working.

**Comment by tameemsafi** [comment]
You can use the `<br>` html tag in the string passed to write on a new line

```js
const instance = new Typewriter('#typewriter', {
  strings: ['Test line 1<br>Test new line'],
  autoStart: true,
  loop: true,
});
```
