### ISSUE TITLE
I'm getting an error!

### ISSUE THREAD

**Issue by Sephirothusa** [tameemsafi/typewriterjs#14]
Uncaught ReferenceError: Typewriter is not defined
    at typewriter.js:11

Not sure whats going on here, could you pls help me? Thank you

**Comment by qroft** [comment]
I am having the same problem, but with me it is a bit more complicated.
I want to use your typewriter script inside a mobile app done with Framework7 and phonegap.
as soon as i add the "import Typewriter from 't-writer.js';" line into my code, nothing works.
It seems to be a hurlde by importing modules into a mobile app, i am not sure.

Is there a walkaround for this, to define "Typewriter" somewhere else?

Greetings and thanks!
Qroft.

**Comment by AndyLIUMel** [comment]
Hi qroft, seems you need to tranlate it to es5 and use require to included the code, as your env does not support es6.
