### ISSUE TITLE
Add types for `state` and other properties

### ISSUE THREAD

**Issue by jimmycrequer** [tameemsafi/typewriterjs#141]
Thanks for providing this very convenient library !

I found out about [this issue](https://github.com/tameemsafi/typewriterjs/issues/30) mentioning about the `state` property, holding the `eventQueue` array.

When I printed out the object to see the available properties, I found out that a lot of them weren't declared in the type :

![Screenshot from 2022-03-03 15-15-12](https://user-images.githubusercontent.com/26185218/156507421-9be3d18a-3123-4807-b0ca-5fc7abb28d15.png)

My goal is to simulate a game dialog behavior where clicking on a message being typed out would just show it entirely.
For this purpose I am clearing the `eventQueue` manually to remove all pending events and write out the whole message at once.

https://jsfiddle.net/eszvo40g/1/

However, Typescript complains because `state` is not defined in the TypewriterClass class. My workaround is currently to extend the type by myself :

```ts
type TypewriterClassExtended = TypewriterClass & { state: { eventQueue: [] } };
```

Would it be possible to add all missing properties in the TypewriterClass class?

**Comment by tameemsafi** [comment]
The state object is supposed to be private therefore should not be included in the external types. This is because it may change in the future.
