### ISSUE TITLE
Please update the documentation

### ISSUE THREAD

**Issue by Dylan-at-LION** [tameemsafi/typewriterjs#18]
Hi there, nice tool you have made here. I found that the option that is referred to as `typingSpeed` on your [website](https://safi.me.uk/typewriterjs/) is actually called `delay` in the code itself. Since you still seem to be updating this I thought you might want to keep the documentation current.

**Comment by tameemsafi** [comment]
@Dylan-at-LION Thanks for letting me know, I updated the documentation website now.
