### ISSUE TITLE
Typewriter pauses typing when browser tab is switched (Next.js)

### ISSUE THREAD

**Issue by hritikb27** [tameemsafi/typewriterjs#180]
I am using this code in my Nextjs application where a message comes from backend and then I render a component with the message as prop where typewriter-effect is being used in this similar manner:

```
import Typewriter from 'typewriter-effect';

const RenderMessage = ({ message }) => {
  return (<Typewriter
  onInit={(typewriter) => {
    typewriter.typeString(message)
      .callFunction(() => {
        console.log('String typed out!');
      })
      .callFunction(() => {
        console.log('All strings were deleted');
      })
      .start();
  }}
/>)
}
```

### **Current behaviour:**
Issue is, as soon as the user changes his browser tab, the typewriter library stops typing and after a while when user opens the tab again, it continues typing the text from the when user switched the tab.

### **Expected behaviour:**
Typewriter should continue typing the text and complete typing the whole string even when the application tab is not active or the browser is minimized.

**Comment by andrii-trush** [comment]
@hritikb27 Is there any updates about this issue?

**Comment by levanion** [comment]
I have the same issue

**Comment by okradze** [comment]
@hritikb27 Hey, can you share your custom component snippet please?

**Comment by hritikb27** [comment]
I created a gist for it, it uses some states that might not be required but use it as you like:- [Custom React Typewriter gist](https://gist.github.com/hritikb27/8c9a822e8f4b8ebeca86e7354317e174)

**Comment by tameemsafi** [comment]
The current approach uses `requestAnimationFrame` and it is expected to pause when switching tabs. Please read this page for more info: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#:~:text=requestAnimationFrame()%20calls%20are%20paused%20in%20most%20browsers%20when%20running%20in%20background%20tabs%20or%20hidden%20%3Ciframe%3Es%20in%20order%20to%20improve%20performance%20and%20battery%20life.

```
requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)s in order to improve performance and battery life.
```

**Comment by cancan2016** [comment]
Has anyone solved this problem?
