### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by benediktvaldez** [tameemsafi/typewriterjs#184]
## Is it safe to assume this project has been abandoned?

There doesn't seem to have been any meaningful work on it since Nov 2020, except for updating some dependencies and merging a few type related PRs. Currently there are 62 issues that aren't really being managed and 13 open PRs, many of which with simple and valid changes that given the time should be easy to tackle.

Please don't take this as criticism on you @tameemsafi, just wondering if you'd be interested in passing this on to someone else to maintain, or at least help you maintain it, if you don't have the time/interest to do so?

I'm willing to help out/take over!

_If_ you'd prefer to hand it over completely, I'd love to keep the repo (so we don't lose all the issues and PRs) and npm package name etc which would require some handover.

**Comment by tameemsafi** [comment]
@benediktvaldez Thanks for the feedback, I have not had much time to take a look at the issues. I would be happy to allow maintainers for the repo, but I will need to update the github actions to that it can publish to npm after a PR has been merged. Currently I have to do that manually, so I will try and make the change by today.

**Comment by benediktvaldez** [comment]
That's great news @tameemsafi, thanks for a prompt reply and reaction. Feel free to reach out if you want (whatever you prefer via https://valdez.is).

**Comment by wparad** [comment]
It looks like now the repo has the npm token included in the build, but there are still lots of open issues and pull requests. I'm trying to decide whether or not my company should fork this repo to start merging this stuff in, or if some of these changes will actually make it in. Any insight you have @tameemsafi would be awesome.

**Comment by tameemsafi** [comment]
I will be addressing the issues, most of them are suggestions or feature requests. So if it is an urgent bug please make it clear in the issue title and it will be fixed.

**Comment by wparad** [comment]
Awesome, glad to hear it
