### ISSUE TITLE
Follow-on typewriters

### ISSUE THREAD

**Issue by woodpd** [tameemsafi/typewriterjs#193]
I'd like to get different parts of my pages to use a typewriter one after the other, but have not found a way to chain them together sequentially, is this possible?

e.g. I have 7 different <section> in the page and my intention is to use typewriter in the first one and then once its completed typing, start typing the second section's content and so on. The `pauseFor` functionality kind of does this, but that's no good really as the content is dynamic and changes in length

**Comment by tameemsafi** [comment]
You can use the `callFunction` method to run a callback one the typewriting effect has completed. You can use that to chain them together.

**Comment by Lejio** [comment]
Yes, what I have done is have a useState and conditionally render the follow-on part once the first part is done typing (using the callFunction).
