### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by diptasahacse** [tameemsafi/typewriterjs#194]
I am getting issues while using in Next JS,

**Type.tsx**
import React from "react";
import Typewriter from "typewriter-effect";
const Type = () => {
  return (
    <Typewriter
      options={{
        strings: ["JavaScript", "TypeScript", "React", "NextJS", "NodeJS"],
        autoStart: true,
        loop: true,
        deleteSpeed: 50,
      }}
    />
  );
};

export default Type;

I used that components in another component like,

**Hero.tsx**

import React from "react";
import Type from "../Shared/Type";
const Hero = () => {
  return (
    <div className="hero min-h-screen bg-base-200">
        <div>
            <Type />
          </div>
    </div>
  );
};

export default Hero;

**Comment by Al-Ghoul** [comment]
Add `'use client'; `to the top of your file.

**Comment by sangayt1997** [comment]
@Al-Ghoul use client on top work well in my case

**Comment by nishantshah977** [comment]
`"use client"` isn't working for me. I tried add it in page.js but didn't work. I also created a new file used `"use client"` and exported in page.js but it also didn't work.
