### ISSUE TITLE
TypewriterJS not working in Shadow DOM

### ISSUE THREAD

**Issue by thenaim** [tameemsafi/typewriterjs#196]
I have been using TypewriterJS library for creating typewriter animations, and it works great in regular DOM elements. However, when attempting to use it within a Shadow DOM environment, the typewriter does not work as expected. 

Steps to Reproduce:
1. Create a Shadow DOM container element.
2. Append a child element within the Shadow DOM container, where the typewriter animation should be applied.
3. Initialize TypewriterJS on the child element with appropriate options and text content.
4. Trigger the typewriter animation.

Expected Behavior:
TypewriterJS should apply the typewriter animation effect on the text content within the Shadow DOM, just like it does in regular DOM elements.

Actual Behavior:
The typewriter animation does not work within the Shadow DOM.

Demo: 
[with shadow dom](https://stackblitz.com/edit/react-shadow-dom-bszqep?file=src%2Findex.js%3AL11-L11) 
[without shadow dom](https://stackblitz.com/edit/react-shadow-dom-oi3aom?file=src%2Findex.js%3AL11)

**Comment by tameemsafi** [comment]
Shadow DOM is not supported at the moment
