### ISSUE TITLE
Bug when deleting chars in subsequent run, even on the main site

### ISSUE THREAD

**Issue by ovicrisan** [tameemsafi/typewriterjs#197]
Even on the sample page at https://safi.me.uk/typewriterjs/ in the 'Results' tab there is a bug when running 2nd or more time - deleteChars() is deleting too much.

In the 1st run we have at some point 'Strings can be **altered!**', but on 2nd run it will be just 'Strings **altered!**' and then even worse.
Are you seeing this?

**Comment by tameemsafi** [comment]
Yes there was a bug in the previous version which is used as the demo on the site. You can see the latest version `2.20.1` working here: https://jsfiddle.net/mv612vrf/1702/

**Comment by ovicrisan** [comment]
The error is still there on JS Fiddle, just let it run a bit.

**Comment by YongThePsibor** [comment]
still there. 
![image](https://github.com/tameemsafi/typewriterjs/assets/136299750/1ca82525-5130-4867-89a6-27f169e40704)
