### ISSUE TITLE
How long is the time interval between letters when the delay option is set to 0?

### ISSUE THREAD

**Issue by x86chi** [tameemsafi/typewriterjs#198]
How long is the time interval between type effects between letters when the delay option is set to 0?

In other typing effect libraries on mobile, setting the delay to 0 causes the typing effect to skip, so I would like to know the default offset between typing effects when the delay option is set to 0 in this library.

**Comment by tameemsafi** [comment]
The delay will be the one passed in the options or by using the `changeDelay` method. There is also `deleteSpeed` and the method `changeDeleteSpeed`.

By default delay is between 120, 160 and delete speed is between 40, 80.
