### ISSUE TITLE
Typewriter paused when tab/window is not active

### ISSUE THREAD

**Issue by jbmyid** [tameemsafi/typewriterjs#203]
When the tab is not active it pauses the animation till it becomes active and resumes.

Is there any way to disable this?

**Comment by tameemsafi** [comment]
It is currently using the `requestAnimationFrame` api, you can read more about it here: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#:~:text=requestAnimationFrame()%20calls%20are%20paused%20in%20most%20browsers%20when%20running%20in%20background%20tabs%20or%20hidden%20%3Ciframe%3Es%20in%20order%20to%20improve%20performance%20and%20battery%20life.
