### ISSUE TITLE
There is no speed setting

### ISSUE THREAD

**Issue by apoklyak** [tameemsafi/typewriterjs#28]
There is no speed adjustment of words typing.

**Comment by tameemsafi** [comment]
@apoklyak You can use the `changeDelay` function to change typing speed of each character.

**Comment by apoklyak** [comment]
@tameemsafi how can I set the speed faster?

**Comment by realgs** [comment]
Read the readme file at https://github.com/tameemsafi/typewriterjs 
and set the delay using changeDelay() function to a desirable value. You can use this function attaching it after "." in the chain of your instructions for the TypeWriter component. The lower the delay the faster the animation will be.

**Comment by danielesavasta** [comment]
I've had same issue wıth changeDelay() and changeDeleteSpeed() as soon as I add them to the chain it just stop working. What am I doing wrong?
eg
typewriter.deleteAll()
            .pauseFor(1000)
            .typeString('<a onclick="changeScr(3);"><strong>Welcome</strong></a>')
            .typeString(' to ')
            .typeString('<a onclick="changeScr(1);"><strong>Hello World</strong></a>')
            .changeDelay(100)
            .typeString(' Bye.')
            .start();

**Comment by tameemsafi** [comment]
@danielesavasta Please make sure you are using the latest version.

You can use it from cdn inside of a file with this link:
`https://unpkg.com/typewriter-effect@latest/dist/core.js`
