### ISSUE TITLE
Clear method?

### ISSUE THREAD

**Issue by jesperlandberg** [tameemsafi/typewriterjs#30]
Is there any way to clear/reset the typewriter to its initial state? I want to be able to interupt it an restart if from the beginning. Possible?

**Comment by tameemsafi** [comment]
At the moment no but you can use a callback method and delete the element from the DOM and reinitialise the typewriter.

Example: https://jsfiddle.net/8arobk2c/2/

**Comment by llibdude** [comment]
Just as a note, i found that this works for my needs:
```javascript
typewriterRef.current.state.eventQueue = []
```

In my case I am using the React component and keep a ref to the typewriter object.  Setting the eventQueue to empty array does reset the queue. I'm sure there is something wrong with what I'm doing but for now its fine :)
