### ISSUE TITLE
jQuery 

### ISSUE THREAD

**Issue by othy54** [tameemsafi/typewriterjs#32]
Hi !

Unfortunatly it doesn't work with jQuery :/
In the console log it give me this error : 

core.js:1 Uncaught TypeError: r.state.elements.container.appendChild is not a function
    at t.setupWrapperElement (core.js:1)
    at t.value (core.js:1)
    at new t (core.js:1)
    at magie.html:57

**Comment by tameemsafi** [comment]
Could you post the code you used? With jQuery you have to make sure you pass the element not the jQuery object.

Example:
```js
var $element = $('.test');

var typewriter = new Typewriter($element[0], {
    loop: true
});
```
