### ISSUE TITLE
Preserve original markup

### ISSUE THREAD

**Issue by marsjaninzmarsa** [tameemsafi/typewriterjs#33]
typewriterjs is blazing fast, but for hero header I want to start with some text in my node already and instantly trigger delete animation via `.deleteAll()`. Tried this, but it won't work as expected (cleaned markup on init):
```
new Typewriter('#typewriter', {
  loop: true,
}).pauseFor(2500)
    .deleteAll()
    .typeString('Strings can be removed')
    .pauseFor(2500)
    .deleteChars(7)
    .typeString('<strong>altered!</strong>')
    .pauseFor(2500)
    .start();
```

Ideally it should be configurable via init params (even more ideally with pause interval between `strings`) as `startFromDelete` or so. Like starting with some text in node, initiating with same text as first of `strings` and skipping initial "typing" part.

**Comment by AndyLIUMel** [comment]
Hi, it is not feasible to display some text instantly as the fps is locked at 60, which means max type speed is 1/60s per char.
A hacking way to do what you want is hiding the text first and then show when deleting.
like this 

https://jsfiddle.net/rhybL7t4/ 

hope it helps
