### ISSUE TITLE
Issues in IE11

### ISSUE THREAD

**Issue by pierrebonny** [tameemsafi/typewriterjs#34]
Your project is still having issues on Internet explorer 11, 
"Unable to get property 'removeChild' of undefined or null reference"
I've tested one of you're examples and it's also not working on IE11 (chatbot example)

**Comment by AndyLIUMel** [comment]
Hi, I have tested on my win 10 IE11, it is working, did you update to the lastest version?

**Comment by tameemsafi** [comment]
There was a small issue in IE11 which was not removing nodes. I have fixed this now in v2.5.3.

**Comment by pierrebonny** [comment]
thanks I'll test it soon

**Comment by pierrebonny** [comment]
Perfect it's working like a charm ! thanks
