### ISSUE TITLE
[Feature Request] CHANGE_CURSOR event request.

### ISSUE THREAD

**Issue by helloye** [tameemsafi/typewriterjs#38]
Hihi,

There was a closed issue that somewhat relates to this: https://github.com/tameemsafi/typewriterjs/issues/13

The `callFunction((state) => ....)` solution that was suggested in the above issue does not seem to work for me. Below is the snippet/context of the code that I'm using it in:

```
  typewriter.typeString("Hi there, what's your name?")
    .callFunction((state) => {
      state.elements.cursor.style = 'none';
    })
    .start();
```

On that note, just wondering if you would be open to adding a `CHANGE_CURSOR` event? Willing to look into/raise a PR for this.

Thanks!

**Comment by tameemsafi** [comment]
You will need to set the display property on the style object to `none`.

See example below:

```js
typewriter.typeString('Hello world?')
    .callFunction(function(state) {
    	state.elements.cursor.style.display = 'none';
    })
    .start();
```

You can make a PR for the `CHANGE_CURSOR` and I would be happy to take a look at it.

**Comment by helloye** [comment]
Cool thanks. Raised PR for this: https://github.com/tameemsafi/typewriterjs/pull/40
Let me know if this is ok.
