### ISSUE TITLE
Using icons e.g. fontawesome

### ISSUE THREAD

**Issue by magicmb** [tameemsafi/typewriterjs#42]
We're able to use **fontawesome** icons in TypewriterJS, which is absolutely fab, however any text after the icon is not displayed for some reason

e.g.

`.typeString('We think TypewriterJS is just fab and <i class="far fa-heart"></i> all the features and options')`

will render 

> We think TypewriterJS is just fab and ♡

and omit "**all the features and options**"

​
PS using CDN: unpkg.com/typewriter-effect/dist/core.js

**Comment by tameemsafi** [comment]
It is fixed now with the latest version.

Exampe:
https://jsfiddle.net/rx6pg9ky/
