### ISSUE TITLE
[Feature Request] Text instantly appear

### ISSUE THREAD

**Issue by ThomasKeast** [tameemsafi/typewriterjs#43]
Hey there,

Currently messing around and loving this package right now. 

I was just working on something small and I wanted to make text appear instantly using the typewriter library. Splitting the typewriter call with jQuery hasn't worked either.

Would love it if there was a .StringShow() or .AppearString() just instantly display the string rather than type it out.

Hope this isn't too much to add, would love to see it!

**Comment by tameemsafi** [comment]
Could you provide a more detailed example? The main point of this package is to have the animation instead of displaying text instantly.
