### ISSUE TITLE
'./node_modules/React/react'.

### ISSUE THREAD

**Issue by MrSimsek** [tameemsafi/typewriterjs#45]
Hi, first of all, thank you for this component. It is very easy to use.

My issue is after I updated my dependencies to their latest releases, I can't start the development server. The error is as follows;

Failed to compile.
./node_modules/typewriter-effect/dist/react.js
Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/React/react'.

I researched a bit and found [this issue in webpack repo](https://github.com/webpack/webpack/issues/5073#issuecomment-505225857) The suggestion seems to edit the `externals` property in webpack config. I think `react: "React"` causing this issue.

Older versions are working fine. 2.8.2 seems to have this problem.

**Comment by thomasjonas** [comment]
Same problem here when using this package with Create React App 3.0.1. It started working for me when I used 2.7.1.

**Comment by tameemsafi** [comment]
@thomasjonas  @MrSimsek I have published a new version `2.9.0` please let me know if that fixes the issue for you.
