### ISSUE TITLE
This package breaks a "Next.js" application

### ISSUE THREAD

**Issue by Shaker-Hamdi** [tameemsafi/typewriterjs#46]
So, here's the situation ...

While the application is running in development mode and installing this package via another terminal window, it works great, exactly like you want it.

However, once you stop the server and try to `"npm run dev"` once again, it breaks the app, and it gives this error ...

![image](https://user-images.githubusercontent.com/3071511/64065627-0fe94680-cc10-11e9-84c6-b2c9bf51e707.png)

I tried this multiple times just to be sure, with every time completely deleting the "node_modules" folder and starting fresh.

**Comment by tameemsafi** [comment]
@Shaker-Hamdi This error is usually because it is running the code in node which does not have access to the window object. Could you let me know how you have setup you app? which webpack plugins are you using?

**Comment by Shaker-Hamdi** [comment]
@tameemsafi I initialized the project using the default webpack for next.js app by running "npx create-next-app". I didn't modify anything in the webpack configuration, you can give it a try and use the package while running the project and then kill the server and start the project again, then it'll give you the same error.

I ended up using this package which was working fine with my project ...
https://www.npmjs.com/package/react-rotating-text

**Comment by roma-glushko** [comment]
@tameemsafi @Shaker-Hamdi the same issue comes when I require typewriterjs to the default gatsby starter project: 
https://github.com/roma-glushko/roma-glushko.github.io

Output during `gatsby build` command:
<img width="1351" alt="2019-09-17_16-24-40" src="https://user-images.githubusercontent.com/9402690/65045553-b00cd280-d967-11e9-88a5-d0f3f8905195.png">

Any ideas on how to fix this issue?

**Comment by Shaker-Hamdi** [comment]
@roma-glushko Just use the package I referenced in my first comment, or this one, which is pretty cool as well ...
https://www.npmjs.com/package/react-typed

**Comment by tameemsafi** [comment]
@Shaker-Hamdi @roma-glushko I have fixed this issue now. This is related to webpack 4 issue, which has now been fixed in webpack 5 (https://github.com/webpack/webpack/pull/8625).
