### ISSUE TITLE
Tags will not diplay

### ISSUE THREAD

**Issue by Airo1011** [tameemsafi/typewriterjs#48]
I tried adding the <br> tag and it didn't work, then I tried using the strong tag and that failed. I am unsure whether its my fault or it's the code which is facing errors. 

Example:
.typeString('and <br>this is my Portfolio')

**Comment by Forz70043** [comment]
can you post all code ?

**Comment by Airo1011** [comment]
```
Js File
var app = document.getElementById('brand');

var typewriter = new Typewriter(app, {
    loop: true
});

typewriter.typeString('My name is <br> Aditya Modi')
    .pauseFor(2000)
    .deleteAll()
    .typeString('and this is <br> my Portfolio')
    .pauseFor(2000)
    .deleteAll()
    .typeString("so welcome to")
    .pauseFor(2000)
    .deleteAll()
    .typeString("Aditya Modi")
    .pauseFor(2000)
    .deleteChars(3)
    .typeString(".")
    .start()

Html
<section id= brand-background>
            <h1 id=brand>Aditya M.</h1>
</section>
```

**Comment by jesussuarz** [comment]
Hi, I had a good time trying to look because it didn't work for me either.

you must first place the library and then the javascript code.

you must also do it under the library of jquery.

**Comment by Airo1011** [comment]
<script src="js/core.js"></script>
<script src="js/script.js"></script>

Is this what you are talking about? Core.js is the Typewrite Library, Script.js is where I place the Javascript above.

**Comment by tameemsafi** [comment]
@Airo1011 I have taken a look and the code you posted above works file. Can you try use the latest version of the package?

JSFiddle of the code you posted above
https://jsfiddle.net/0edm5nL1/
