### ISSUE TITLE
Static text infront of the typeString

### ISSUE THREAD

**Issue by cirquit** [tameemsafi/typewriterjs#49]
Is it possible to have a static text variable which will not be deleted? I couldn't find any examples and simply prepending a `<span> my static text </span>` results in a typing animation which starts from the right-to-left instead of the usual left-to-right.

See this example - https://www.tmeyer.info

**Comment by cirquit** [comment]
I'd be open to implement it myself and open a pull request if you can point me to the right direction - if this is also something you might want to provide as an additional feature.

**Comment by tameemsafi** [comment]
You can have some text before the container element that you use, this way it will always be visible.

HTML:
```html
<div><span>TEXT HERE: </span><span id="typewriter-container"></span></div>
```

JS:
```
new Typewriter('#typewriter-container', {
  strings: ['Hello', 'World'],
  autoStart: true,
});
```

**Comment by cirquit** [comment]
I think you misunderstood my problem. I'd like the same effect as the site I posted - at the initial load the text area is blank, then some text appears, for example "Alex says hello world!". In the next step, everything gets deleted besides "Alex", so that word stays there and the next animation would start from that word onward by adding e.g "says goodbye".

What is shown in steps:

1. "" (on load)
2. "Alex says hello world" (after finishing first animation)
3. "Alex" (after deleting up everything up to Alex)
4. "Alex says goodbye" (finishing the second animation)

**Comment by tameemsafi** [comment]
@cirquit Please see jsfiddle example link below to achieve the effect you have described

https://jsfiddle.net/mpx94c8j/2/
