### ISSUE TITLE
changeDelay doesn't work

### ISSUE THREAD

**Issue by ManonJK** [tameemsafi/typewriterjs#53]
When I use the changeDelay option to modify the speed of the typing effect, nothing appends, whatever the value is

**Comment by adambctld** [comment]
I think I had to use the `delay` option in order for that to work correctly.

**Comment by mikepeiman** [comment]
Same for me with both changeDelay and changeDeleteSpeed, neither is working for me, while the rest of the plugin works fine

**Comment by tameemsafi** [comment]
You will need to pass in a number as the delay param.

Example:
```js
const typewriter = new Typewriter(app, {
  delay: 75
});

typewriter
  .typeString("A simple yet powerful native javascript")
  .changeDelay(20)
  .changeDeleteSpeed(20)
```
