### ISSUE TITLE
setting innerHTML "breaks" chain?

### ISSUE THREAD

**Issue by bigteejay** [tameemsafi/typewriterjs#56]
I saw you [response](https://github.com/tameemsafi/typewriterjs/issues/30#issuecomment-457010711) to this other similar issue.

Following the advice there, [I set the innerHTML to an empty string](https://jsfiddle.net/dz97w0fy/), but no matter what I do, the chain seems to break.  Am I doing something wrong?

**Comment by bigteejay** [comment]
[This](https://jsfiddle.net/t51fngkp/) seems hacky, but "works".

Is there a better/easier way that I've missed?

**Comment by bigteejay** [comment]
Note:  this applies to 2.3.1 (as in examples) and 2.12.2/"latest"

**Comment by tameemsafi** [comment]
This is because the loop system relies on the DOM elements being available. If you reset the innerHTML, you will be removing all the DOM nodes and therefore it will not work when it tries to delete characters. I think the solution you have is the best solution if you need to reset the innerHTML.
