### ISSUE TITLE
string option does not work when array is passed as props

### ISSUE THREAD

**Issue by carljustineoyales** [tameemsafi/typewriterjs#57]
**Working**
`<Typewriter 
            options={{
            strings: [
              "test1","test2","test3"
            ],
            autoStart: true,
            loop: true,
            
          }}/>`

**Not Working**
`
<Typewriter 
            options={{
            strings: this.props.typewriter,
            autoStart: true,
            loop: true,
            
          }}/>`

**Comment by tameemsafi** [comment]
@carljustineoyales What is the value of `this.props.typewriter`, it should be an array of strings

**Comment by carljustineoyales** [comment]
Parent Component

`` 
this.state = {
 typewriter:[test1,test2,test3]
}

<ChildComponent typewriter={typewriter}/>
``

Child Component

``
<Typewriter 
options={{
strings:this.props.typewriter
}}/>

**Comment by tameemsafi** [comment]
You should see an error in the console if you open developer tools, can you post what that message says?

**Comment by carljustineoyales** [comment]
@tameemsafi there's no error related to the component. I move the props data to the component state and still there's no output even though there's a value on the string option when view via react dev tools
