### ISSUE TITLE
Define fallback HTML when typewriterjs is not loaded

### ISSUE THREAD

**Issue by hrvstr** [tameemsafi/typewriterjs#62]
I noticed that typewriterjs fails to load on older devices such as my iPhone 5 running iOS 10.3.4.
Newer iPhones seem to be working (tested in iOS simulator).
Is it possible to define some fallback HTML for this situation?

**Comment by tameemsafi** [comment]
Yes you can insert some fall back html within the container element, if the javascript code works then it will remove it and override it.

```html
<span id="app">Some text here</span>
```

```js
var app = document.getElementById('app');

var typewriter = new Typewriter(app, {
  loop: true,
  delay: 75,
});

typewriter
  .pauseFor(2500)
  .typeString('Some text here')
  .start();
```
