### ISSUE TITLE
`deleteSpeed` does not get propagated to React component

### ISSUE THREAD

**Issue by MartinSeeler** [tameemsafi/typewriterjs#65]
It seems that the `deleteSpeed` property is missing / not used in the React component. Is this on purpose or just a bug?

**Comment by dishcandanty** [comment]
Seems like the property just needs to be added here: https://github.com/tameemsafi/typewriterjs/blob/master/src/react/Typewriter.js#L50

**Comment by dishcandanty** [comment]
Was able to fix by manually patching the deleteSpeed. PR above.

**Comment by tameemsafi** [comment]
@MartinSeeler Can you confirm if it has been fixed using v2.13.1 as the PR above by @dishcandanty is now merged?

**Comment by MartinSeeler** [comment]
@tameemsafi Yes, after upgrading to `2.13.1` the `deleteSpeed` can be changed.
@dishcandanty thx for the fix
