### ISSUE TITLE
Feature Request: Delete Immediately 

### ISSUE THREAD

**Issue by wdfinch** [tameemsafi/typewriterjs#66]
First off I really like the package. Great job to everyone who has worked on it. I was wondering if it was possible or would it be possible to add a feature to clear the text managed by the typewriter immediately rather than having to use a delay. 

If there is a lot of text on the screen, it can take a really long time to delete it all before the new text can be shown to the user. 

For example, I'm using the project to create a terminal like effect in a web browser and there can be a ton of text already from previous user actions. It would be nice if this text could be removed immediately rather than making the user sit there and watch it all be deleted.

Thanks.

**Comment by TeleworkInc** [comment]
I added this feature for you in my own fork with the `clearWrapper` method, pull request is pending: https://github.com/TeleworkInc/typewriterjs

**Comment by mathieuflamant** [comment]
@wdfinch You should be able to achieve this by using a callback function which manipulates the wrapper

```
    typewriter
        .callFunction((e) => {
            e.elements.wrapper.innerHTML=''
        })
        .start()
```
