### ISSUE TITLE
Git tags and license for project

### ISSUE THREAD

**Issue by dakshshah96** [tameemsafi/typewriterjs#8]
Hey @tameemsafi,

I'd like to host your library, typewriterjs on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

* The git auto-updater for cdnjs relies on [git tags](https://github.com/moappi/json2html/tags) to recognize a release version and automatically update the library in the cdnjs repo.
* We also need to know what license your project comes under so we can mention it appropriately.

If it's not too much to ask, can you please do the following:

* Add git tags for this repository
* Add the license of your project to the repository (e.g. MIT, Apache-2.0, etc.)

**Comment by tameemsafi** [comment]
Hello Daksh,

Thank you for your interest in my project.

I have added git tag for version 1.0.0 and also the MIT license.

Kind regards,
Tameem

**Comment by dakshshah96** [comment]
Thanks for the quick response @tameemsafi!
Much appreciated 👍
