### ISSUE TITLE
Option to not add a new line

### ISSUE THREAD

**Issue by vineet8588** [tameemsafi/typewriterjs#81]
In react component, whenever some text is written after the Typewriter component, that text is rendered in a new line. I want to continue it without new line.
Any option to do that?

**Comment by timi-codes** [comment]
You can achieve this by overriding the wrapper styles display property
```
.Typewriter{
  display: inline-block;
}
```

**Comment by vineet8588** [comment]
Thanks, I am not good with css

> You can achieve this by overriding the wrapper style display property
> 
> ```
> .Typewriter{
>   display: inline-block;
> }
> ```

Thanks, I am not good with css.
