### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by raziqraif** [tameemsafi/typewriterjs#84]
It would be nice if this library is supported in Typescript as well.

**Comment by natterstefan** [comment]
Hi @raziqraif,

I think is resolved by now with https://github.com/tameemsafi/typewriterjs/pull/82 and the additional changes pushed into the main branch (see version 2.17.0). Please, correct me if I am wrong @tameemsafi.

**Comment by Jbarget** [comment]
I can confirm typescript types are included with the package when i installed v.2.17.0  just now 👍🏼
