### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by MDSilviu** [tameemsafi/typewriterjs#9]
Thank you for the plugin, it';s a good one, doing the job that others don't.
I got a few suggestions for you.
Consider removing the developer mode and also all the console errors for myself using it means i want the smallest possible file size to add in the project and all those messages even if they are useful if you are not doing something correctly you have a documentation for it and people will figure things out and removing those things will reduce the file size.
Adding an option  for the delay between the end of deleting the string and starting to write again, right now i see you add a random delay that it can't be controlled, i wanted no delay between deleting and starting again over a preset list of strings, i was simply initiating it with the strings as options from the start.
Another thing would be to remove the cursor animation from the javascript and let people use a css option. This does the job 
@keyframes blink{
  0% { opacity:1; }
  50% { opacity:0; }
  100% { opacity:1; }
}
.typed-cursor{
  opacity: 1;
  animation: blink 1s infinite;
}

**Comment by tameemsafi** [comment]
Hello Manolache,

Thank you for your suggestions.

I will update the code when I get some time.

**Comment by tameemsafi** [comment]
I have updated it now to use css keyframes for blinking in v2.
